In [10]:
import numpy 
import pandas as pd
import matplotlib
from sklearn import preprocessing

file_path = "/Users/vikasramaneti/workspace/CS677/P2-nv-p2/src/main/java/edu/usfca/cs/mr/outputs/corn_result.csv"
def load_corn_production_data(file_path=file_path):
    return pd.read_csv(file_path, sep="\s+", names=["GeoHash", "Year", "Max_Day_Temp", "Min_Day_Temp", "Max_Night_Temp", "Min_Night_Temp", "Avg_Temperature", "Avg_Precipitation"])

corn_data = load_corn_production_data()
corn_data["Avg_Precipitation"] = corn_data["Avg_Precipitation"]*((10512*7)/12)
sorted_data = corn_data.sort_values("Min_Day_Temp", ascending=False)
sorted_data

,GeoHash,Year,Max_Day_Temp,Min_Day_Temp,Max_Night_Temp,Min_Night_Temp,Avg_Temperature,Avg_Precipitation
17,8e3xz,2019,31.2,13.7,25.7,14.1,21.822094,82.400160
15,8e3xz,2017,31.2,13.7,25.7,14.1,22.379524,144.156109
27,8e3xz,2015,31.2,13.7,25.7,14.1,22.668695,294.063298
26,8e3xz,2014,31.2,13.7,25.7,14.1,22.285913,192.453329
25,8e3xz,2013,31.2,13.7,25.7,14.1,21.827164,123.050353
...,...,...,...,...,...,...,...,...
1391,bsqrj,2014,28.6,-30.7,28.3,-30.9,3.567373,16.733079
1390,bsqrj,2019,28.6,-30.7,28.3,-30.9,-3.615657,30.678531
1389,bsqrj,2018,28.6,-30.7,28.3,-30.9,0.946322,17.334872
1388,bsqrj,2017,28.6,-30.7,28.3,-30.9,2.570281,26.731522
1387,bsqrj,2016,28.6,-30.7,28.3,-30.9,3.792707,25.264656

In [11]:
corn_data_filter = corn_data[corn_data.Avg_Temperature<=24][corn_data.Avg_Temperature>=20][corn_data.Avg_Precipitation>=45][corn_data.Avg_Precipitation<=60]
corn_data_filter

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

,GeoHash,Year,Max_Day_Temp,Min_Day_Temp,Max_Night_Temp,Min_Night_Temp,Avg_Temperature,Avg_Precipitation
200,9r0z3,2009,45.3,-2.1,37.6,0.7,21.859472,47.628270
334,9t97t,2006,40.6,-3.2,35.9,-2.7,21.599543,50.425919
342,9t97t,2014,40.6,-3.2,35.9,-2.7,21.245518,49.933183
734,9wmv1,2010,37.5,-5.8,32.7,-5.4,20.567047,48.688632
744,9wncj,2017,42.2,-6.4,39.4,-6.2,21.275616,52.483371
...,...,...,...,...,...,...,...,...
2120,dp15v,2007,37.4,-3.8,31.6,-4.1,20.827106,48.028951
2156,dpjve,2016,36.3,-2.0,32.9,-2.1,20.435446,52.757294
2204,dqdh0,2010,38.7,3.2,33.3,2.7,23.132833,54.962327
2207,dqdh0,2013,38.7,3.2,33.3,2.7,21.457127,58.167790
2209,dqdh0,2015,38.7,3.2,33.3,2.7,22.367373,53.652701

In [13]:
grouped = corn_data_filter.groupby("GeoHash")
grouped.groups #

{'9r0z3': Int64Index([200], dtype='int64'),
 '9t97t': Int64Index([334, 342], dtype='int64'),
 '9wmv1': Int64Index([734], dtype='int64'),
 '9wncj': Int64Index([744, 749, 755], dtype='int64'),
 '9wwuw': Int64Index([825], dtype='int64'),
 '9wx8p': Int64Index([828, 829, 835], dtype='int64'),
 '9wxb0': Int64Index([837, 842, 849], dtype='int64'),
 '9ybjn': Int64Index([1060, 1063], dtype='int64'),
 '9ygq3': Int64Index([1074, 1082], dtype='int64'),
 '9yqez': Int64Index([1096], dtype='int64'),
 '9yssz': Int64Index([1108], dtype='int64'),
 '9ywy0': Int64Index([1117, 1122], dtype='int64'),
 '9z5ps': Int64Index([1130], dtype='int64'),
 '9zjfb': Int64Index([1185, 1190, 1191, 1192], dtype='int64'),
 'dj3tb': Int64Index([1630], dtype='int64'),
 'dj8xv': Int64Index([1646, 1654], dtype='int64'),
 'dj9t7': Int64Index([1658], dtype='int64'),
 'djcbw': Int64Index([1689, 1693], dtype='int64'),
 'djcdn': Int64Index([1697, 1699], dtype='int64'),
 'djdte': Int64Index([1746], dtype='int64'),
 'djdug': Int64Index([1765], dtype='int64'),
 'djecq': Int64Index([1769], dtype='int64'),
 'djefj': Int64Index([1783], dtype='int64'),
 'djfyc': Int64Index([1816], dtype='int64'),
 'djndg': Int64Index([1821], dtype='int64'),
 'djqp6': Int64Index([1835], dtype='int64'),
 'djyjv': Int64Index([1850, 1851], dtype='int64'),
 'dn0qh': Int64Index([1877, 1882], dtype='int64'),
 'dn1eu': Int64Index([1886, 1889, 1890, 1891], dtype='int64'),
 'dn1tv': Int64Index([1905, 1907], dtype='int64'),
 'dn1vh': Int64Index([1913, 1926], dtype='int64'),
 'dn468': Int64Index([1927, 1930, 1931], dtype='int64'),
 'dn4e7': Int64Index([1943], dtype='int64'),
 'dn4g5': Int64Index([1953, 1954, 1957, 1962], dtype='int64'),
 'dn4v7': Int64Index([1966, 1969], dtype='int64'),
 'dn5he': Int64Index([1977, 1981, 1982], dtype='int64'),
 'dn7ky': Int64Index([1991, 1996], dtype='int64'),
 'dndev': Int64Index([2010, 2011], dtype='int64'),
 'dnfmn': Int64Index([2028, 2031], dtype='int64'),
 'dng8x': Int64Index([2037], dtype='int64'),
 'dnh8n': Int64Index([2046, 2052, 2054, 2056], dtype='int64'),
 'dnm39': Int64Index([2060], dtype='int64'),
 'dnru8': Int64Index([2094, 2096, 2099], dtype='int64'),
 'dp15v': Int64Index([2120], dtype='int64'),
 'dpjve': Int64Index([2156], dtype='int64'),
 'dqdh0': Int64Index([2204, 2207, 2209], dtype='int64')}